### ISSUE TITLE
error on console

### ISSUE THREAD

**Issue by russopie** [Tera-Shiraneko/lazyrootbeer#1]
error: S_LOGIN<10>..name: invalid offset for ".name" at 298 (inside header)
    at parseField (D:\CaaliTeraProxyToolBox\node_modules\tera-data-parser\lib\protocol\index.js:414:23)
    at TeraProtocol.parse (D:\CaaliTeraProxyToolBox\node_modules\tera-data-parser\lib\protocol\index.js:431:7)
[11:56:31.370] [dispatch] handle: error running hook for S_LOAD_TOPO<3>
hook: (anonymous) in tera-game-state
data: { zone: 7031,
  loc: Vec3 { x: 34051, y: 10632, z: 6379 },
  quick: false }
error: Cannot read property 'includes' of undefined
    at Me.<anonymous> (D:\CaaliTeraProxyToolBox\mods\lazyrootbeer\index.js:58:35)
    at Me.emit (events.js:199:15)
    at Me.setZone (D:\CaaliTeraProxyToolBox\mods\tera-game-state\lib\me.js:144:18)
    at Object.callback (D:\CaaliTeraProxyToolBox\mods\tera-game-state\lib\me.js:60:18)
[11:56:59.486] [dispatch] handle: error running hook for S_LOAD_TOPO<3>
hook: (anonymous) in tera-game-state
data: { zone: 7015,
  loc: Vec3 { x: -2273, y: 87616, z: -1315 },
  quick: false }
error: Cannot read property 'includes' of undefined
    at Me.<anonymous> (D:\CaaliTeraProxyToolBox\mods\lazyrootbeer\index.js:58:35)
    at Me.emit (events.js:199:15)
    at Me.setZone (D:\CaaliTeraProxyToolBox\mods\tera-game-state\lib\me.js:144:18)
    at Object.callback (D:\CaaliTeraProxyToolBox\mods\tera-game-state\lib\me.js:60:18)

**Comment by Tera-Shiraneko** [comment]
First it cant be that it's using S_LOGIN version 10. Just delete the module and redownload it again here should work fine afterwards.
