### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by alfonsolaraivan** [Tera-Shiraneko/lazyrootbeer#2]
error: Cannot read property 'includes' of undefined
    at handle (C:\Users\user\AppData\Local\Programs\CaaliTeraProxy\mods\lazyrootbeer-master\index.js:107:31)
    at Object.Lazy_Rootbeer.mod.hook [as callback] (C:\Users\user\AppData\Local\Programs\CaaliTeraProxy\mods\lazyrootbeer-master\index.js:122:13)
[19:57:50.563] [dispatch] handle: error running hook for C_START_SKILL<7>

**Comment by Tera-Shiraneko** [comment]
Just redownload the module again should work fine afterwards. And don't forget to restart proxy afterwards.
