### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by russopie** [Tera-Shiraneko/lazyrootbeer#2]
error: Cannot read property 'includes' of undefined
    at handle (D:\CaaliTeraProxy\mods\lazyrootbeer\index.js:69:29)
    at Object.Lazyrootbeer.mod.hook [as callback] (D:\CaaliTeraProxy\mods\lazyrootbeer\index.js:96:13)
[21:31:02.105] [dispatch] handle: error running hook for C_START_SKILL<7>
hook: (anonymous) in lazyrootbeer
data: { skill:
   SkillID { reserved: 0, npc: false, type: 1, huntingZoneId: 0, id: 81001 },
  w: 1.537432244658384,
  loc: Vec3 { x: 52254.37109375, y: 117927.2578125, z: 4431.25 },
  dest: Vec3 { x: 0, y: 0, z: 0 },
  unk: true,
  moving: false,
  continue: false,
  target: 3518437209614517n,
  unk2: false }

**Comment by Tera-Shiraneko** [comment]
If the module isn't working redownload it cause the config changed and doesn't get overridden with auto update.
